grift: update for new directory structure
riscv/riscv-arch-test pull request #128
Opened 2020-07-29 15:00 UTC by nmeum

The directory structure was changed in
5a978cfd444d5e640150d46703deda99057b2bbb. However, as stated in
this commit it was only tested with riscvOVPsim and spike.
Unfortunately, the commit broke the grift target as paths weren't
adjusted accordingly for it.

2020-12-04 14:40 UTC, MarcKarasek approved these changes

2020-12-04 14:42 UTC, MarcKarasek commented on riscv-target/grift/device/rv32i/Makefile.include
> -	$$(RISCV_OBJDUMP) -D $(work_dir_isa)/$$@ > $(work_dir_isa)/$$@.objdump
i think you missed one of the $$@ that should be here.  The first one in the line will only be $@ instead of $$@

2020-12-04 14:42 UTC, MarcKarasek requested changes
See inline comments

2020-12-07 17:09 UTC, nmeum commented on riscv-target/grift/device/rv32i/Makefile.include
> -	$$(RISCV_OBJDUMP) -D $(work_dir_isa)/$$@ > $(work_dir_isa)/$$@.objdump
Could you elaborate a bit? Which exact line you are referring to? I am a bit confused as there are a lot of `$$@` in this diff :sweat_smile:

2021-03-20 02:13 UTC, allenjbaum commented on riscv-target/grift/device/rv32i/Makefile.include
> -	$$(RISCV_OBJDUMP) -D $(work_dir_isa)/$$@ > $(work_dir_isa)/$$@.objdump
MArc is pointing at he first $$@, which is at the end of line 24, and it should be just $@ if I'm interpreting his comments correctly.
IF this is correct Marc, could you comment? 
And please update this and close this if Marc agrees.

**Note** that the entire riscv-target/grift directory should be moved back into the grift home repo as we will be removing all target directories  at some point in the (near) future, replacing it with a pointer to your repo (preferrable as a top level arch_test_target directory to avoid this kind of issue entirely. 
See github.com/riscv/riscv-arch-test/riscv-target/spike/ for what will remain
and github.com/riscv/riscv-isa-sim/arch_test_target/spike/README.md as example documentation

2021-04-27 21:24 UTC, allenjbaum commented
This needs to be resolved, or I'm going to close it without the PR being merged

2021-04-27 21:27 UTC, benjaminselfridge commented
I think it's safe to just remove support for grift -- grift was dormant for a bit but is now going through some significant updates. When those are done, I will circle back and see what needs to be done to add support for the compliance framework. Until then, I suggest you don't worry about it. :)

2021-04-28 05:23 UTC, allenjbaum commented
This is not being actively worked on, so removing by request.

2021-04-28 05:23 UTC, closed without merging